export const categories = [
  "all categories",
  "food",
  "Electronics & gadgets",
  "Fashion & clothing",
  "Beauty & Skincare",
  "Hair products",
  "Footwears",
  // "Fashion & clothing",
  // "Fashion & clothing",
  // "Fashion & clothing",
  // "Fashion & clothing",
];

export const promotionData = {
  itemName: "Laptop Stand",
  oldPrice: "3,000",
  newPrice: "3,000",
  text: "Get your laptop stand, phone stand and mouse pad all for",
  imgUrl: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
};

export const products = [
  {
    id: 1,
    name: "Silk Scarf",
    categories: "Fashion & Clothing",
    size: "-",
    price: "#9,999",
    src: "/images/products/product1.png",
  },
  {
    id: 2,
    name: "Dr Martens Loafers",
    categories: "Fashion & Clothing",
    size: "38 - 45",
    price: "#54,999",
    src: "/images/products/product2.png",
  },
  {
    id: 3,
    name: "Dr Martens Loafers",
    categories: "Fashion & Clothing",
    size: "-",
    price: "#9,999",
    src: "/images/products/product3.png",
  },
  {
    id: 4,
    name: "Tote bag",
    categories: "Fashion & Clothing",
    size: "-",
    price: "#54,999",
    src: "/images/products/product4.png",
  },

  {
    id: 5,
    name: "Cargo pants",
    categories: "Fashion & Clothing",
    size: "-",
    price: "#9,999",
    src: "/images/products/product5.png",
  },

  {
    id: 6,
    name: "Travelling bag",
    categories: "Fashion & Clothing",
    size: "-",
    price: "#54,999",
    src: "/images/products/product6.png",
  },
  {
    id: 7,
    name: "Knuckle rings",
    categories: "Fashion & Clothing",
    size: "38 - 45",
    price: "#9,999",
    src: "/images/products/product7.png",
  },
  {
    id: 8,
    name: "Nike slide",
    categories: "Fashion & Clothing",
    size: "-",
    price: "#54,999",
    src: "/images/products/product8.png",
  },
  {
    id: 9,
    name: "Belts",
    categories: "Fashion & Clothing",
    size: "",
    price: "#9,999",
    src: "/images/products/product9.png",
  },
  {
    id: 10,
    name: "New balance sneakers",
    categories: "Fashion & Clothing",
    size: "38 - 45",
    price: "#54,999",
    src: "/images/products/product10.png",
  },
];
