import React from "react";

export const metadata = {
  title: "Futamart | Login",
  description: "Generated by create next app",
};
export default function LoginLayout({ children }) {
  return <main>{children}</main>;
}
