"use client";
import {
  AnalyticsIcon,
  ChatIcon,
  DashboardIcon,
  Logo_White,
  LogoutIcon,
  NotificationIcon,
  ProductIcon,
  SettingIcon,
} from "@/assets";
import { DashboardSidebar } from "@/components/dashboardSidebar";
import Link from "next/link";
import { usePathname } from "next/navigation";
import React from "react";

// export const metadata = {
//   title: "Futamart | Dashboard",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <>
      <main className="flex  bg-black p-5 w-full h-[100vh] overflow-hidden">
        <DashboardSidebar />
        <main className="w-[100%] bg-[#F2F3F4] rounded-[16px] px-10 py-10">{children}</main>
      </main>
    </>
  );
}
