import React from "react";

export const metadata = {
  title: "Futamart | Register",
  description: "Generated by create next app",
};
export default function RegisterLayout({ children }) {
  return <main>{children}</main>;
}
